/* 24 December 2007
 *
 * Yuri Arapov <yuridichesky@gmail.com>
 *
 * Project Euler
 *
 * http://projecteuler.net/index.php?section=problems&id=2
 *
 * Problem 2
 * 19 October 2001
 *
 * Each new term in the Fibonacci sequence is generated by
 * adding the previous two terms. By starting with 1 and 2, the
 * first 10 terms will be:
 *
 *   1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 *
 * Find the sum of all the even-valued terms in the sequence
 * which do not exceed one million.
 *
 * Answer:
 *      1089154
 *
 * Done.
 *
 * Some useful references:
 *   http://en.wikipedia.org/wiki/Fibonacci_sequence
 *   http://en.wikibooks.org/wiki/Fibonacci_number_program
 *   http://mathworld.wolfram.com/FibonacciNumber.html
 */
#include <stdio.h>

int foo(int argc, char *argv[])
{
        int f1 = 1, f2 = 2, f = 2, fo;
        for (;;) {
                if (f % 2 == 0) {
                        printf("%8d", f);
                        if (f > 2)
                                printf(" = %d*%6d + %5d", f / fo, fo, f % fo);
                        printf("\n");
                        fo = f;
                }
                f = f1 + f2;
                if (f > 1000000)
                        break;
                f1 = f2;
                f2 = f;
        }
        /* ... and this is how I fugured out that
         *
         * F  = 4 * F    + F
         *  i        i-1    i-2
         */
}


int main(int argc, char *argv[])
{
        int f_1 = 2, f_2 = 0, f = 2, s = 0;
        for (; f <= 1000000; ) {
                s += f;
                f = 4*f_1 + f_2;
                f_2 = f_1;
                f_1 = f;
        }
        printf("%d\n", s);
}
