package main

import "fmt"

func main() {
	// Each new term in the Fibonacci sequence is generated by adding the previous two
	// terms. By starting with 1 and 2, the first 10 terms will be:
	//
	// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
	//
	// By considering the terms in the Fibonacci sequence whose values do not exceed
	// four million, find the sum of the even-valued terms.
	//
	// Answer: 4613732

	const maxFib = 4_000_000

	fibPrev := 0
	fib := 1

	sum := 0

	for {
		if fib > maxFib {
			break
		}
		if fib%2 == 0 {
			sum += fib
		}
		fib, fibPrev = fib+fibPrev, fib
	}

	fmt.Println(sum)
}
